name: Build ReturnYTCast

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.6

      - name: Build
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: ReturnYTCast
          path: packages/*.deb
